CMakeLists.txt, source/Common/MaaConf.h, source/Controller/Platform/PosixIO.cpp, source/Controller/Platform/PosixIO.h, source/Utils/Locale.hpp, source/Utils/Logger.hpp, source/Utils/Platform/PlatformWin32.cpp
1. cmake文件增加编译器分支判断
2. 增加编译选项-Wno-unused-parameter(gcc)
3. 解决linux(gcc 13.1.1)下各种编译问题
=> Linux下编译问题

source/Base/AsyncRunner.hpp, source/Controller/Platform/PosixIO.cpp, source/Utils/Locale.hpp
1. ansi_to_utf8、utf8_to_ansi、utf8_to_unicode_escape实现
2. 合并冲突代码
=> Locale.hpp部分实现

README.md
=> Update README.md add MAAIP

.github/workflows/ci.yml, CMakeLists.txt, cmake/nuget.cmake, pkgs/nupkgs/Maa.Framework.Runtimes.nuspec
=> ci: 添加 nupkgs 打包与发布流程

.github/workflows/ci.yml
fix and perf https://github.com/MaaAssistantArknights/MaaFramework/actions/runs/6091667386
=> ci: 修复ci发版错误

README.md
=> docs: 增加使用 MaaFramework 的项目: MAALimbusCompany 边狱公司 小助手

tools/ImageCropper/README.zh_cn.md, tools/ImageCropper/colormatcher.py, tools/ImageCropper/main.py, tools/ImageCropper/requirements.txt, tools/ImageCropper/roi.py, tools/ImageCropper/roimage.py
=> refactor: 重构 ImageCropper

README.md, README_en.md, docs/en_us/1-1.QuickStarted.md, docs/en_us/2-1.Integration.md, docs/en_us/2-2.CallbackProtocol.md, docs/en_us/3-1.PipelineProtocol.md
=> docs: add English docs

include/Interface/proto/instance.proto, include/MaaFramework/Instance/MaaInstance.h, include/MaaToolKit/Device/MaaToolKitDevice.h, sample/cpp/main.cpp, source/MaaFramework/API/MaaInstance.cpp, source/MaaFramework/API/MaaTypes.h, source/MaaFramework/Instance/InstanceMgr.cpp, source/MaaFramework/Instance/InstanceMgr.h, source/MaaRpc/implement/Instance.cpp, source/MaaRpc/implement/Instance.h, source/MaaToolKit/API/MaaToolKitDevice.cpp, source/MaaToolKit/AdbDevice/DeviceAPI.h, source/MaaToolKit/AdbDevice/DeviceMgr.cpp, source/MaaToolKit/AdbDevice/DeviceMgr.h
fix https://github.com/MaaAssistantArknights/MaaFramework/issues/121
=> [Breaking change] refactor: more async APIs

sample/python/__main__.py, source/binding/Python/maa/buffer.py, source/binding/Python/maa/context.py, source/binding/Python/maa/controller.py, source/binding/Python/maa/custom_action.py, source/binding/Python/maa/custom_recognizer.py, source/binding/Python/maa/define.py, source/binding/Python/maa/future.py, source/binding/Python/maa/instance.py, source/binding/Python/maa/library.py, source/binding/Python/maa/library.pyi, source/binding/Python/maa/resource.py, source/binding/Python/maa/toolkit.py
=> feat: 优化 Python 绑定

.github/workflows/doc.yml, .gitignore, Doxyfile, include/MaaFramework/Instance/MaaController.h, include/MaaFramework/Instance/MaaCustomController.h, include/MaaFramework/Instance/MaaInstance.h, include/MaaFramework/Instance/MaaResource.h, include/MaaFramework/MaaAPI.h, include/MaaFramework/MaaDef.h, include/MaaFramework/MaaMsg.h, include/MaaFramework/Task/MaaCustomAction.h, include/MaaFramework/Task/MaaCustomRecognizer.h, include/MaaFramework/Task/MaaSyncContext.h, include/MaaFramework/Utility/MaaBuffer.h, include/MaaFramework/Utility/MaaUtility.h, include/MaaToolkit/Config/MaaToolkitConfig.h, include/MaaToolkit/Device/MaaToolkitDevice.h, include/MaaToolkit/Win32/MaaToolkitWin32Window.h
我自己的fork先部署了一份
https://spie.cc/MaaFramework/index.html
先看看有没有写得不对的吧（
=> docs: Add Doxygen documents

README.md, README_en.md
=> docs: README中的项目实践添加语言标签

README.md, README_en.md
向README.md中增加新的最佳实践 [MRA](https://github.com/NaNExist/ResonanceAssistant)
=> docs: 申请增加最佳实践：列车长 小助手

.github/workflows/build.yml, .github/workflows/test.yml, .vscode/settings.json, cmake/config.cmake, cmake/grpc-gen.cmake, cmake/macos.cmake, cmake/thrift-gen.cmake, cmake/utils.cmake, cmake/version.cmake, source/CMakeLists.txt, source/LibraryHolder/CMakeLists.txt, source/MaaAdbControlUnit/CMakeLists.txt, source/MaaDbgControlUnit/CMakeLists.txt, source/MaaFramework/CMakeLists.txt, source/MaaProjectInterface/CLI/CMakeLists.txt, source/MaaProjectInterface/Impl/CMakeLists.txt, source/MaaThriftControlUnit/CMakeLists.txt, source/MaaWin32ControlUnit/CMakeLists.txt, test/dlopen/CMakeLists.txt, test/pipeline/CMakeLists.txt
=> fix: macOS link error

include/MaaFramework/MaaDef.h, include/MaaFramework/Utility/MaaBuffer.h, include/MaaFramework/Utility/MaaUtility.h, source/MaaFramework/API/MaaBuffer.cpp, source/MaaFramework/API/MaaUtility.cpp, source/MaaFramework/Buffer/ImageBuffer.hpp, source/MaaFramework/Buffer/ListBuffer.hpp, source/MaaFramework/Buffer/StringBuffer.hpp, source/MaaFramework/Vision/CustomRecognizer.cpp
=> feat: ListBuffer

.github/workflows/build.yml, tools/nupkgs/Maa.Framework.Runtimes.nuspec
#208
来看看 cmake 和 python 要不要改
---
- tag: 由 v `${tag#v}` - `ci.${commit_次数}` - `${commit_hash}`
改变为 v `${tag#v}` - `post.${commit次数}` - `ci.${{ github.run_id }}`
- version: `${tag#v}` - `post.${commit次数}` - `ci.${{ github.run_id }}` + `${commit_hash}` . `${date%Y%m%d}`
=> rfc(#208): new version number scheme

tools/pipeline.schema.json
- 字段`action`支持`InputText`/`Text`值
- 字段`action`支持`StopTask`值
- 支持字段`detector`
- 支持字段`ratio`
- 支持字段`input_text`
- 修复模式依赖无效的问题(fixed #218)
- 修复字段`recognition`值为`FeatureMatch`或`ColorMatch`时字段`count`冲突问题
- 修复字段`recognition`值为`OCR`、`NeuralNetworkClassify`或`NeuralNetworkDetect`时字段`model`冲突问题
- 修复字段`recognition`值为`TemplateMatch`或`NeuralNetworkDetect`时字段`threshold`冲突问题
- 修复字段`action`值为`Click`时字段`target`和`target_off`和`wait_freezes`中字段`target`和`target_off`冲突问题
- 修复字段`action`值为`StartApp`或`StopApp`时字段`package`冲突问题
=> chore: update pipeline.schema.json

README.md
为README最佳实践添加了MCCA，强迫症顺便删了两个空格
=> 为README最佳实践添加了新项目

.github/workflows/doc.yml, include/MaaFramework/Instance/MaaController.h, include/MaaFramework/Instance/MaaCustomController.h, include/MaaFramework/Instance/MaaInstance.h, include/MaaFramework/Instance/MaaResource.h, include/MaaFramework/Task/MaaCustomRecognizer.h, include/MaaFramework/Task/MaaSyncContext.h, include/MaaFramework/Utility/MaaUtility.h, include/MaaToolkit/ExecAgent/MaaToolkitExecAgent.h, tools/Doxygen/Doxyfile
https://github.com/MaaXYZ/MaaApiConverter
=> feat: 添加 index.json 构建用于 MaaApiConverter

source/MaaAdbControlUnit/Base/UnitBase.h, source/MaaAdbControlUnit/Manager/ControlUnitMgr.cpp, source/MaaAdbControlUnit/Manager/ControlUnitMgr.h, source/include/Utils/Dispatcher.hpp
=> perf: 改用观察者模式同步adb分辨率变动

README.md, README_en.md
=> docs: 更新物华弥新最佳实践

.github/workflows/build.yml, .github/workflows/doc.yml, .github/workflows/meta.yml, .github/workflows/test.yml
Co-authored-by: nekosu <liao.hy@outlook.com>
=> chore: perf ci

docs/zh_cn/3.1-任务流水线协议.md
=> docs: 修复 文档错误

README.md, README_en.md
=> docs: 最佳实践添加MET

docs/en_us/2.1-Integration.md, docs/zh_cn/2.1-集成文档.md
- 接口情况：
- 全功能可用 ✔️
- 提供 sample ✔️
- CI 单元测试 ✔️
- 标准化接口 ✔️
- 协议解析封装 ❌
- [仓库地址](https://github.com/hanhuoer/maa-framework-java)
- [下载地址](https://central.sonatype.com/namespace/io.github.hanhuoer)
- [集成示例](https://github.com/hanhuoer/maa-framework-java/blob/main/maa-sample/README.md)
- [单元测试](https://github.com/hanhuoer/maa-framework-java/blob/main/maa-core/src/test)
=> docs: add MaaFramework.Binding.Java

include/MaaFramework/MaaDef.h, source/MaaFramework/Resource/OCRResMgr.cpp, source/MaaFramework/Resource/OCRResMgr.h, source/MaaFramework/Resource/ONNXResMgr.cpp, source/MaaFramework/Resource/ONNXResMgr.h, source/MaaFramework/Resource/ResourceMgr.cpp, source/MaaFramework/Resource/ResourceMgr.h, source/MaaProjectInterface/Impl/Runner.cpp, source/binding/Python/maa/define.py, source/binding/Python/maa/resource.py, source/include/ProjectInterface/Types.h
=> feat: use gpu by default

README.md, README_en.md, docs/zh_cn/4.2-标准化接口设计.md
=> docs: 添加 MaaYYs 最佳实践，优化文档格式

README.md, README_en.md
=> docs: 添加最佳实践 MPA

docs/en_us/2.1-Integration.md, docs/zh_cn/2.1-集成文档.md, sample/csharp/main.csx, sample/csharp/pi_cli.csx
[![](https://img.shields.io/badge/NuGet-Maa.Framework-%23004880)](https://www.nuget.org/packages/Maa.Framework) [![](https://img.shields.io/badge/NuGet-Maa.Framework.Native-%23004880)](https://www.nuget.org/packages/Maa.Framework.Native) [![](https://img.shields.io/badge/NuGet-Binding-%23004880)](https://www.nuget.org/packages/Maa.Framework.Binding) [![](https://img.shields.io/badge/NuGet-Native-%23004880)](https://www.nuget.org/packages/Maa.Framework.Binding.Native)
- 接口情况：
- 全功能可用 ✔️
- 提供 sample ✔️
- CI 单元测试 ✔️
- 标准化接口 ✔️
- 回调封装：NotificationCallback 包装为 Callback 事件，其他包装为接口
- 协议解析封装 ❌
- [仓库地址](https://github.com/MaaXYZ/MaaFramework.Binding.CSharp)
- [下载地址](https://www.nuget.org/packages/Maa.Framework)
- [集成示例](https://github.com/MaaXYZ/MaaFramework/tree/main/sample/csharp)
- …
=> docs: add MaaFramework.Binding.CSharp

README.md, README_en.md
用electron写的，是的电脑上又多了一个chromium
=> docs: README 添加 MAAGUI 索引

include/MaaFramework/Instance/MaaTasker.h, source/MaaFramework/API/MaaTasker.cpp, source/MaaFramework/API/MaaTypes.h, source/MaaFramework/Task/EmptyTask.h, source/MaaFramework/Tasker/Tasker.cpp, source/MaaFramework/Tasker/Tasker.h, source/binding/Python/maa/tasker.py
fix https://github.com/MaaXYZ/MaaFramework/issues/439
@MaaXYZ/binding-developers
=> feat: post stop return task_id

test/python/binding_test.py
for https://github.com/MaaXYZ/MaaFramework/pull/441
=> test: tasker.post_stop

source/MaaToolkit/AdbDevice/AdbDeviceFinder.cpp, source/MaaToolkit/AdbDevice/AdbDeviceFinder.h, source/MaaToolkit/AdbDevice/AdbDeviceWin32Finder.cpp, source/MaaToolkit/AdbDevice/AdbDeviceWin32Finder.h
fix https://github.com/MaaXYZ/MaaFramework/issues/459
=> feat: 改用 MuMuManager 来获取 mumu 模拟器的地址

README.md, README_en.md, docs/en_us/1.1-QuickStarted.md, docs/zh_cn/1.1-快速开始.md
https://github.com/orgs/MaaXYZ/discussions/467#discussioncomment-11577581
=> docs: remove practices

.github/workflows/build.yml
fix https://github.com/MaaXYZ/MaaFramework/issues/479
=> ci: fix release issue

.github/actions/publish_nodejs/action.yml, .github/workflows/build.yml, .github/workflows/publish_nodejs.yml
=> ci: refactor nodejs puslish

source/MaaFramework/Task/Component/Actuator.cpp, source/MaaFramework/Task/Context.cpp, source/MaaFramework/Task/Context.h, source/MaaFramework/Task/PipelineTask.cpp, source/MaaFramework/Task/PipelineTask.h
=> fix: fix StopTask not work

README.md, README_en.md
修复了QQ群里提到的千年之旅的pipeline logo与其他项目不一致的问题
=> docs: 统一最佳实践的Pipeline图标

source/binding/Python/maa/custom_recognition.py
fix https://github.com/MaaXYZ/MaaFramework/issues/585
=> fix(python): RectType type checking error

include/MaaFramework/Instance/MaaTasker.h, source/Common/MaaTasker.cpp, source/MaaAgentClient/Client/AgentClient.cpp, source/MaaAgentClient/Client/AgentClient.h, source/MaaAgentServer/RemoteInstance/RemoteTasker.cpp, source/MaaAgentServer/RemoteInstance/RemoteTasker.h, source/MaaFramework/Tasker/Tasker.cpp, source/MaaFramework/Tasker/Tasker.h, source/binding/Python/maa/tasker.py, source/include/Common/MaaTypes.h, source/include/MaaAgent/Message.hpp, test/python/binding_test.py
fix https://github.com/MaaXYZ/MaaFramework/issues/580
@MaaXYZ/binding-developers 干活了.jpg
=> feat: tasker stopping

README.md, README_en.md
=> docs: 添加最佳实践 MNMA

README.md, README_en.md
=> docs: 添加最佳实践YAMaaPE

source/MaaToolkit/AdbDevice/AdbDeviceFinder.cpp
fix https://github.com/MaaXYZ/MaaFramework/issues/636
fix https://github.com/MAA1999/M9A/pull/332
=> feat: waydroid check

3rdparty/include/meojson/reflection/jsonization.hpp, source/MaaFramework/Resource/PipelineParser.cpp, source/MaaFramework/Resource/PipelineTypesV2.h, source/binding/NodeJS/release/maa-node/src/pipeline.ts
@moomiji @neko-para @MaaXYZ/binding-developers
=> feat: remove `_` for `template` field

docs/en_us/3.1-PipelineProtocol.md, docs/zh_cn/3.1-任务流水线协议.md, source/MaaFramework/Controller/ControllerAgent.cpp, source/MaaFramework/Controller/ControllerAgent.h, source/MaaFramework/Resource/PipelineDumper.cpp, source/MaaFramework/Resource/PipelineParser.cpp, source/MaaFramework/Resource/PipelineParser.h, source/MaaFramework/Resource/PipelineTypes.h, source/MaaFramework/Resource/PipelineTypesV2.h, source/MaaFramework/Task/Component/Actuator.cpp, source/MaaFramework/Task/Component/Actuator.h, source/binding/NodeJS/release/maa-node/src/pipeline.ts
fix: https://github.com/MaaXYZ/MaaFramework/issues/717
只有 Pipeline，不涉及 API
=> feat: LongPressKey

README.md, README_en.md
=> docs: 将 YAMaaPE 最佳实践同步迁移为 MaaPipelineEditor

.github/workflows/build.yml, .github/workflows/test.yml, CMakePresets.json, tools/maadeps-download.py
=> feat: use custom clang
